# Few-Shot Object Detection Configuration

# General settings
general:
  device: "cuda"  # Use "cuda" or "cpu"
  random_seed: 42

# Paths
paths:
  meta_trained_model: "models/fasterrcnn_meta_trained.pth"
  fine_tuned_model: "models/fasterrcnn_finetuned_new_class.pth"
  output_dir: "outputs"

# Dataset settings
dataset:
  meta_train:
    json_path: "C:/Users/User/Desktop/few_shot_detection/coco/annotations_trainval2017/annotations/instances_train2017.json"  # Path to COCO JSON annotation file
    images_path: C:/Users/User/Desktop/few_shot_detection/coco/train2017/train2017"  # Path to images folder
  
  new_class:
    json_path: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test2/_annotations.coco.json"  # Path to new class COCO JSON
    images_path: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test2/support"  # Path to new class images folder
    test_images_folder: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test2/query"  # Path to test images folder

# Model settings
model:
  backbone: "fasterrcnn_resnet50_fpn"
  num_classes: 2  # Background + 1 class for fine-tuning

# Meta-learning settings
meta_learning:
  num_epochs: 50
  ways: 20  # N-way classification
  shots: 15  # K-shot learning
  batch_size: 2
  lr: 0.0001

# Fine-tuning settings
fine_tuning:
  num_epochs: 10
  batch_size: 2
  lr: 0.005
  momentum: 0.9
  num_classes: 12

# Inference settings
inference:
  image_path: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/train/jp6_jpg.rf.70c7eb83525469db9f592e105946ede2.jpg"  # Can be a single image file or a directory
  conf_threshold: 0.5
  batch_size: 1  # Batch size for processing multiple images
  save_visualizations: true  # Whether to save images with bounding boxes
  output_format:


