# Few-Shot Object Detection Configuration

# General settings
general:
  device: "cuda"  # Use "cuda" or "cpu"
  random_seed: 42

# Paths
paths:
  meta_trained_model: "models/fasterrcnn_meta_trained.pth"
  fine_tuned_model: "models/fasterrcnn_finetuned_new_class.pth"
  output_dir: "outputs"

# Dataset settings
dataset:
  meta_train:
    json_path: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/_annotations.coco.json"  # Path to COCO JSON annotation file
    images_path: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/train"  # Path to images folder
  
  new_class:
    json_path: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/_annotations.coco.json"  # Path to new class COCO JSON
    images_path: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/train"  # Path to new class images folder
    test_images_folder: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/train"  # Path to test images folder

# Model settings
model:
  backbone: "fasterrcnn_resnet50_fpn"
  num_classes: 2  # Background + 1 class for fine-tuning

# Meta-learning settings
meta_learning:
  num_epochs: 10
  ways: 1  # N-way classification
  shots: 5  # K-shot learning
  batch_size: 2
  lr: 0.0001

# Fine-tuning settings
fine_tuning:
  num_epochs: 10
  batch_size: 2
  lr: 0.005
  momentum: 0.9

# Inference settings
inference:
  image_path: "C:/Users/User/Desktop/few_shot_detection/kaggle/input/oxalis-coco/train/jp9_jpg.rf.d80f4ab806ee1c359c44df92a4dcf5c5.jpg"  # Can be a single image file or a directory
  conf_threshold: 0.5
  batch_size: 1  # Batch size for processing multiple images
  save_visualizations: true  # Whether to save images with bounding boxes
  output_format: