# Few-Shot Object Detection Configuration

# General settings
general:
  device: "cuda"  # Use "cuda" or "cpu"
  random_seed: 42

# Paths
paths:
  meta_trained_model: "models/fasterrcnn_meta_trained.pth"
  fine_tuned_model: "models/adapted_model.pth"
  output_dir: "outputs"

# Dataset settings
dataset:
  meta_train:
    json_path: "C:/Users/User/Desktop/few_shot_detection/coco/annotations_trainval2017/annotations/instances_train2017.json"  # Path to COCO JSON annotation file
    images_path: "C:/Users/User/Desktop/few_shot_detection/coco/train2017/train2017"  # Path to images folder
  
  new_class:
    json_path: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test2/_annotations.coco.json"  # Path to new class COCO JSON
    images_path: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test2/support"  # Path to new class images folder
    test_images_folder: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test2/query"  # Path to test images folder

# Model settings
model:
  backbone: "fasterrcnn_resnet50_fpn"
  num_classes: 2  # Background + 1 class for fine-tuning

# Meta-learning settings
meta_learning:
  num_epochs: 5
  ways: 5  # N-way classification
  shots: 5  # K-shot learning
  batch_size: 2
  lr: 0.0001

# Fine-tuning settings
fine_tuning:
  num_epochs: 20
  batch_size: 8
  lr: 0.005
  momentum: 0.9
  num_classes: 13
  ways: 10
  shots: 10  # K-shot learning
# Inference settings
inference:
  image_path: "C:/Users/User/Desktop/few_shot_detection/FasterRCNN_FewShotLearning/NewClassData/test1/query/jp27_jpg.rf.c1c95e5a7435ea11e91271362e1b1d94.jpg"  # Can be a single image file or a directory
  conf_threshold: 0.00001
  batch_size: 1  # Batch size for processing multiple images
  save_visualizations: true  # Whether to save images with bounding boxes
  output_format:

